name: Build

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-rust:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: "x86_64-pc-windows-gnu"
            name: dioxus.dll
          - target: "x86_64-unknown-linux-gnu"
            name: libdioxus.so
          - target: "aarch64-unknown-linux-gnu"
            name: libdioxus.so
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}
          workspaces: rust

      - name: Install cross
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cross

      - name: Build
        working-directory: rust
        run: cross build --target ${{ matrix.target }} --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: rust/target/${{ matrix.target }}/release/${{ matrix.name }}
          if-no-files-found: error

  build-plugin:
    runs-on: ubuntu-latest
    needs: build-rust
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Move artifacts to resources
        run: |
          mkdir -p src/main/resources/win32-x86-64
          mv artifacts/x86_64-pc-windows-gnu/dioxus.dll src/main/resources/win32-x86-64/dioxus.dll
          mkdir -p src/main/resources/linux-x86-64
          mv artifacts/x86_64-unknown-linux-gnu/libdioxus.so src/main/resources/linux-x86-64/libdioxus.so
          mkdir -p src/main/resources/linux-aarch64
          mv artifacts/aarch64-unknown-linux-gnu/libdioxus.so src/main/resources/linux-aarch64/libdioxus.so

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: gradle

      - name: Build plugin
        run: ./gradlew buildPlugin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin
          path: build/distributions/*.zip
          if-no-files-found: error
