name: Build

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-rust:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: "x86_64-pc-windows-gnu"
            name: dioxus.dll
          - target: "x86_64-unknown-linux-gnu"
            name: libdioxus.so
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-targets: false

      - name: Install cross
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cross

      - name: Build
        working-directory: rust
        run: cross build --target x86_64-pc-windows-gnu --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}
          path: rust/target/${{ matrix.target }}/release/${{ matrix.name }}
